#!/bin/bash


read -p "Enter the file or directory for backup:" oneinput

read -p "Enter the road for saveing backup:" twoinput

count=1

if [ ! -e "$oneinput" ]; then
	echo "This file or directory is fail"
	exit
fi

if [ ! -d "$twoinput" ]; then
	echo "dont redy ; create it"
	mkdir -p "$twoinput"
fi

backup_name="$(basename "$oneinput")-$(date +%Y-%m-%d-%H:%M).tar.gz"

tar cfzv "$twoinput/$backup_name" --checkpoint=.10 "$oneinput"

cowsay -f tux "*** Your backup was successful ***"
